POST http://localhost:3001/ai/extract/cv
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.txt"

< ./my_cv.pdf
--WebAppBoundary--

###


